services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: quiz_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
